### ISSUE TITLE
add create data ( only row )

### ISSUE THREAD

**Issue by HegedusAlexandra** [GDEPROJEKTCSOPI/ivkemence#11]

**Comment by HegedusAlexandra** [comment]
példa:

INSERT INTO Homerseklet (hutopanel_id, adag_id, datumido)
VALUES (1, 2, '2024-10-18 12:00:00');

de nem csak egy panel hanem egy egész sor!

**Comment by kgahor** [comment]
Van 15 hűtőpanel (igazából csak 14, mert a 7-es hiányzik) a csv-ben. Arra gondolsz, hogy minden hűtőpanelhez szúrjak be egy új dátummal egy értéket?

Esetleg egy 7-es hűtőpanelt hozzunk létre ugyanannyi adattal mint a többi és átlagoljuk a mért értékeit a többi hűtőpanel alapján?
